import type { User, Employee, LeaveRequest, AttendanceRecord, Payslip, Announcement } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@company.com',
    password: 'password123',
    firstName: 'John',
    lastName: 'Doe',
    role: 'employee',
  },
  {
    id: '2',
    email: 'admin@company.com',
    password: 'admin123',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
  },
  {
    id: '3',
    email: 'jane.smith@company.com',
    password: 'password123',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'employee',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    userId: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@company.com',
    phone: '+1 (555) 123-4567',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    joinDate: '2021-03-15',
    salary: 125000,
    employmentType: 'Full-time',
    status: 'Active',
  },
  {
    id: 'emp-002',
    userId: '3',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@company.com',
    phone: '+1 (555) 234-5678',
    department: 'Marketing',
    position: 'Marketing Manager',
    joinDate: '2020-08-20',
    salary: 95000,
    employmentType: 'Full-time',
    status: 'Active',
  },
  {
    id: 'emp-003',
    firstName: 'Michael',
    lastName: 'Johnson',
    userId: 'user-3',
    email: 'michael.johnson@company.com',
    phone: '+1 (555) 345-6789',
    department: 'Sales',
    position: 'Sales Executive',
    joinDate: '2022-01-10',
    salary: 85000,
    employmentType: 'Full-time',
    status: 'Active',
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-001',
    employeeId: 'emp-001',
    type: 'Vacation',
    startDate: '2024-05-10',
    endDate: '2024-05-17',
    days: 5,
    reason: 'Personal vacation',
    status: 'Approved',
    createdAt: '2024-04-20',
    approvedAt: '2024-04-22',
    approvedBy: 'admin-1',
  },
  {
    id: 'leave-002',
    employeeId: 'emp-001',
    type: 'Sick',
    startDate: '2024-06-01',
    endDate: '2024-06-01',
    days: 1,
    reason: 'Medical appointment',
    status: 'Pending',
    createdAt: '2024-05-28',
  },
  {
    id: 'leave-003',
    employeeId: 'emp-002',
    type: 'Vacation',
    startDate: '2024-07-01',
    endDate: '2024-07-14',
    days: 10,
    reason: 'Summer vacation',
    status: 'Approved',
    createdAt: '2024-05-15',
    approvedAt: '2024-05-20',
    approvedBy: 'admin-1',
  },
];

export const mockAttendance: AttendanceRecord[] = [
  {
    id: 'att-001',
    employeeId: 'emp-001',
    date: '2024-05-28',
    status: 'Present',
    checkIn: '09:00',
    checkOut: '17:30',
  },
  {
    id: 'att-002',
    employeeId: 'emp-001',
    date: '2024-05-27',
    status: 'Present',
    checkIn: '08:55',
    checkOut: '18:00',
  },
  {
    id: 'att-003',
    employeeId: 'emp-001',
    date: '2024-05-26',
    status: 'Late',
    checkIn: '09:45',
    checkOut: '17:15',
  },
  {
    id: 'att-004',
    employeeId: 'emp-001',
    date: '2024-05-25',
    status: 'Present',
    checkIn: '09:00',
    checkOut: '17:45',
  },
  {
    id: 'att-005',
    employeeId: 'emp-001',
    date: '2024-05-24',
    status: 'Absent',
  },
];

export const mockPayslips: Payslip[] = [
  {
    id: 'payslip-001',
    employeeId: 'emp-001',
    month: 'May',
    year: 2024,
    baseSalary: 10416.67,
    bonus: 2000,
    deductions: 1500,
    netSalary: 10916.67,
    uploadedDate: '2024-05-28',
  },
  {
    id: 'payslip-002',
    employeeId: 'emp-001',
    month: 'April',
    year: 2024,
    baseSalary: 10416.67,
    deductions: 1400,
    netSalary: 9016.67,
    uploadedDate: '2024-04-28',
  },
  {
    id: 'payslip-003',
    employeeId: 'emp-002',
    month: 'May',
    year: 2024,
    baseSalary: 7916.67,
    deductions: 1200,
    netSalary: 6716.67,
    uploadedDate: '2024-05-28',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-001',
    title: 'Company Summer Outing - July 15th',
    content: 'We are excited to announce our summer outing on July 15th! All employees and their families are welcome to join us for a day of fun activities and team bonding.',
    postedBy: 'Admin User',
    postedDate: '2024-05-25',
    priority: 'High',
  },
  {
    id: 'ann-002',
    title: 'New Employee Wellness Program',
    content: 'Starting next month, we are launching a comprehensive wellness program including gym membership discounts, yoga classes, and mental health support services.',
    postedBy: 'HR Department',
    postedDate: '2024-05-20',
    priority: 'Medium',
  },
  {
    id: 'ann-003',
    title: 'System Maintenance - May 31st',
    content: 'Please note that the HRIS system will undergo maintenance on May 31st from 10 PM to 6 AM. The portal will be unavailable during this time.',
    postedBy: 'IT Department',
    postedDate: '2024-05-18',
    priority: 'High',
  },
];
